//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerSchemeSellAndBidding.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmerSchemeDBEntities1 : DbContext
    {
        public FarmerSchemeDBEntities1()
            : base("name=FarmerSchemeDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BankDetail> BankDetails { get; set; }
        public virtual DbSet<BiddingTable> BiddingTables { get; set; }
        public virtual DbSet<ClaimForm> ClaimForms { get; set; }
        public virtual DbSet<Cropprice> Cropprices { get; set; }
        public virtual DbSet<FarmerCropdetil> FarmerCropdetils { get; set; }
        public virtual DbSet<FarmerLand> FarmerLands { get; set; }
        public virtual DbSet<InsuranceApplication> InsuranceApplications { get; set; }
        public virtual DbSet<RollType> RollTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserRegister> UserRegisters { get; set; }
    }
}
